### PR TITLE
Feature improvement

### PR DESCRIPTION
**Pull request by seognil**
I know this repo is for `np`
And I'd like to improve the implement of the function in my experience using `np`

Beside the origin check of which tool the project already used,
It checks if `yarn` command exists while in an empty project
(It's much more cli friendly I think ;)

It is similar to #5
But using a much easier logic,
(only added some case switching in `index.js` file)
(And upgrade the test cases)

Lint and Test passed here before I make the PR.

the API call is not changed, but result maybe varies,
I thought it's necessary to bump a version for public usage if you accepts my PR.

😄😄

### CODE REVIEW

**Comment by sindresorhus** [comment]
What problem does this solve? What's the use-case?

I have `yarn` installed globally because some of the projects I contribute to uses it, but that doesn't mean I want Yarn in new projects.

**Comment by seognil** [comment]
Beacuse someone prefer `yarn` more than `npm`,
And want their toolchain (just like `np`) to use `yarn` as possible.

In my case, `np` will not use `yarn` while start from a boilerplate project (not runned `install`) which I want that to..

Okay...
I see the difference between demands,
maybe fallback to add an option to solve that?

**Comment by sindresorhus** [comment]
> Beacuse someone prefer yarn more than npm,

This goes both ways. Someone might prefer npm over yarn. My point is that your check is ambiguous as it's just guessing, and it will get it wrong at least half the time.

> In my case, np will not use yarn while start from a boilerplate project (not runned install) which I want that to..

Why are you publishing something you haven't even tested?

And for the `np` case, we could maybe change it so that setting `{yarn: true}` forces Yarn even if a `has-yarn` returns false. It would then default to `'auto'`. You could open an `np` issue about that.

**Comment by seognil** [comment]
The problem I got is https://github.com/sindresorhus/np/issues/424
I'am making the test fire of publish process, not to really publish a tool yet.
And `np` also has a `--no-publish` option, to just bump the version for repo.

If with `--no-publish`, why I still need yarn?
Because of the standard-version problem https://github.com/sindresorhus/np/pull/344 
I can achieve that with `yarn config set version-git-message 'chore(release): v%s'` and no other tools.
(commit message example: https://github.com/seognil/npm-feature-test/tree/master)


So the ROOT problem I got is that, not really this one.
And I make sense of the origin logic now.
It's ok for me to keep the logic origin and close this PR
( : this tool self will only check the established project status)

(Maybe a new purpose needs a new package, not an update? 😅)

---

About my PR, I considered that it would be more _cli friendly_.

e.g.`np` has `Installing dependencies using XXX` and `test` steps,
it's a chained tool, he will do the things and free my hand.
so it really doesn't matter what status the folder is,

(But I make sense of the origin logic of this repo now)
(Like you said, to achieve what I exampled above, `{yarn: true}` or `--yarn-preferred` is also a method)

**Comment by sindresorhus** [comment]
> If with --no-publish, why I still need yarn?

There are other operations that are done even if it's not publishing that might require Yarn specific knowledge in a Yarn project.

**Comment by sindresorhus** [comment]
Closing as this is not something I feel fits in this package.

**Comment by seognil** [comment]
Okay...

I found a package called `is-yarn-global` from [update-notifier](https://github.com/yeoman/update-notifier/blob/master/index.js)
It seems to match the feature which I had meant before

I'm a newbie for Github and open source system, sorry for the bother 😅

**Pull request closed without merging**
